### ISSUE TITLE
Errors in Chrome

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/IITC-Button#1]
1. `Unrecognized manifest key 'applications'.`
2. `Uncaught TypeError: Cannot read property 'addEventListener' of null`
  Stack: `app/popup/popup.js:183 (anonymous function)`

**Comment by modos189** [comment]
That is all right)

1 - a warning about an unknown key used for Firefox
2 - added for debugging, it is necessary to delete

**Comment by johnd0e** [comment]
Ok then
