### ISSUE TITLE
Phantom plugins / Should gracefully degrade if plugin status is undefined

### ISSUE THREAD

**Issue by cody-somerville** [IITC-CE/IITC-Button#111]
I've ran into the status of external plugins being undefined (cause still to be determined) which results in the plugin in the plugin list to not show the plugin name and the plugin actions to be pushed out so aren't visible unless you scroll horizontally which is likely not obvious to user so it looks like there is a plugin they can't easily identify or delete. It may be particular plugins that are causing the issue but ideally user should still be able to disable, enable, download, and delete user plugins even if plugin is misbehaving.

![image](https://user-images.githubusercontent.com/356861/235805792-afa2d885-11b7-4f28-b7e2-5af3e0b713d1.png)

**Comment by modos189** [comment]
Unfortunately I have not been able to reproduce the problem. I have prepared a PR that should hide such plugins. I will be glad if you can provide a database of installed plugins (you can post it as gist or send it to me personally in telegram @modos189).

To do this you need:

### In Chrome
1. Go to the list of extensions
2. Click "Debug background.html pages" next to IITC-Button

### In Firefox:

1. Go to the add-ons debugging page `about:debugging#/runtime/this-firefox`
2. Click the "Explore" button next to the IITC-Button

In the console, paste the code and copy the result:

`chrome.storage.local.get(["release_plugins_flat"], data => console.log(JSON.stringify(data)))`

Note that if the observed error is present not in the `release` channel but in the `beta` channel, replace the command accordingly
