### ISSUE TITLE
Wrong pages intercepted

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/IITC-Button#13]
1. This is only page that should be processed: 
 https://github.com/TheSned/IITCPlugins/raw/master/copy-portal-details-for-op-sheet.user.js

2. These pages should not be processed:
   https://github.com/TheSned/IITCPlugins/blob/master/copy-portal-details-for-op-sheet.user.js
   https://github.com/TheSned/IITCPlugins/blame/master/copy-portal-details-for-op-sheet.user.js
   https://github.com/TheSned/IITCPlugins/commits/master/extend-poly-lines.user.js

3. As for pages like https://github.com/TheSned/IITCPlugins/blob/master/copy-portal-details-for-op-sheet.user.js
   It would be perfect to add button (in `div.BtnGroup`) to open file in IITC-Button.

4. It's bad that IITC-Button try to intercept every `*.user.js` file, as there may be scripts not related to IITC.
   Is it possible to check file's content?
   Most IITC plugins have `// @name           IITC plugin: ` line.

5. When IITC-Button turned off it should not intercept anything.
   But it tries, even when I forbid access to pages (via Chrome context menu `This can read and change site data >`)

**Comment by modos189** [comment]
Unfortunately, now I can only close a new tab automatically if the page is not a IITC plugin. Too many restrictions in browsers. Maybe I can find another API later

**Comment by modos189** [comment]
The links are now out of date and unavailable. But the link detection system has been redesigned and now the offer to install a plugin appears only if it is indeed a plugin for IITC
