### ISSUE TITLE
Bug: high utilization of device resources in some cases

### ISSUE THREAD

**Issue by modos189** [IITC-CE/IITC-Button#143]
When scrolling through the google patents page (example: https://patents.google.com/patent/US5443036A/en ), there is a dramatic increase in CPU and RAM utilization. 
The problem is observed in Firefox c Manifest V2 & V3. I have not noticed it in Chrome, the measurements are within the margin of error.

https://www.reddit.com/r/IITC/s/vahxVGsFWQ

**Comment by le-jeu** [comment]
When scrolling frenetically in this page, the browser memory consumption increases and a error triggers about too many calls to API Location or History in a small laps of time (from a script : search-app-vulcanized.js from the page)

Is there some hook in IITC button that run code for such API calls ?

**Comment by modos189** [comment]
No, but I have a suspicion that the page is actively using dispatchEvent() calls and the extension is trying to handle them
