### ISSUE TITLE
Iitc-m Auto draw problems scrolling through bookmarks

### ISSUE THREAD

**Issue by kabusnacks** [IITC-CE/IITC-Button#16]
My iitc-m has recently been having issues. When I go to draw a link, withthe Auto draw function, I can't completely scrolling through my bookmarks.

**Comment by johnd0e** [comment]
Confirmed.
But this is wrong place to report.

**Comment by kabusnacks** [comment]
Where is the right place to report?

**Comment by johnd0e** [comment]
https://github.com/IITC-CE/ingress-intel-total-conversion/issues/

But I've already added your report there, see #221.
