### ISSUE TITLE
@id should not be used

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/IITC-Button#17]
Userscripts should be distinguished by @namespace + @name (only these 2 fields)

Ref: https://wiki.greasespot.net/Metadata_Block#.40name

**Comment by johnd0e** [comment]
@id is excessive
Let's add @author instead (https://github.com/IITC-CE/ingress-intel-total-conversion/pull/229)

**Comment by jujaga** [comment]
Hi - I've just encountered a few issues attempting to load a custom plugin that didn't have the **@id** attribute field specified - it was refusing to take the script. I had to put it in explicitly before the button would accept the script.

Would be good to make sure if the identifiers are supposed to be a composite of **@namespace** and **@name** that it also reflects the implementation.

**Comment by modos189** [comment]
Fixed by changing the data storage scheme to 1.4.0
