### ISSUE TITLE
Some plugins have dependencies, and their scripts must be injected in order.

### ISSUE THREAD

**Issue by ryantheleach** [IITC-CE/IITC-Button#18]
Depending on the (random) order the scripts are being loaded / sorted in on the external scripts, makes several plugins seem to be enabled / disabled at random due to errors.

It would be useful to make load order deterministic and sortable.

In addition, for toggling enabled status of plugins, it would be cool if they could be sorted alphabetically (as opposed to load order) or grouped into folders much like the default plugins are.

**Comment by ryantheleach** [comment]
It's only a suspicion, but I've had several plugins that depend on draw tools being available bomb out randomly, There may be another cause.

**Comment by johnd0e** [comment]
Do not worry. Proper plugins use some techniques so keep things in order, such as `iitcLoaded` hook.
And even more: in upcoming version we will introduce new [`priority`](https://github.com/IITC-CE/ingress-intel-total-conversion/pull/205) property.
