### ISSUE TITLE
Unable to turn off external plugins

### ISSUE THREAD

**Issue by kikifreena** [IITC-CE/IITC-Button#26]
I use external plugins with IITC button (mainly @AlfonsoML button for Pogo s2 cells) because I play both PoGo and Ingress. In PoGo mode, I do want those tools, because they're extremely useful. However, when I'm planning links and looking at unclaimed portals for the latest event (lol), I don't want a zillion stops/gyms showing up everywhere. On mobile IITC I just disable the plugin for now and re-enable it, but I can't seem to turn the plugin on or off.

I'm on Chrome on MacOS.

**Comment by blsmit5728** [comment]
Did you make sure to click the plugin name, not the button. The button doesn't actually switch. Also, once you click the plugin name and it switches the switch, you have to refresh the Intel page.

**Comment by kikifreena** [comment]
That's so frustrating. Are there any plans to make the button actually work?

**Comment by blsmit5728** [comment]
I don't have plans to, but I can see if it's possible.

**Comment by kikifreena** [comment]
Ok now I'm having a new but similar bug. I am trying to turn on some of the stock IITC plugins such as mission, portal info, etc. but immediately after reloading intel, the plugin goes back to being off... I did click the plugin name itself as you suggested.

**Comment by modos189** [comment]
Fixed https://github.com/IITC-CE/IITC-Button/commit/5a0dd7c9a57a4cb957b7df8a189bccd0324665a1
