### ISSUE TITLE
Hot to uninstall external plugins

### ISSUE THREAD

**Issue by elkuku** [IITC-CE/IITC-Button#28]
There is a button to delete external plugins but it doesn't seem to work as expected (like removing the plugin :wink:)

When I click the button it tells me that the changes will be applied after rebooting IITC. But this does not happen - how to reboot IITC?? :confused:

**Comment by GeneralCrime** [comment]
sorry for duplicate.

![Unbenannt](https://user-images.githubusercontent.com/14043077/74866850-d807c400-5353-11ea-9ea8-cdace84914f6.JPG)

i see this in the interface and the delete button does not working

**Comment by modos189** [comment]
Starting with v1.4.0 it should be fixed by changing the storage scheme. Feel free to open this issue again
