### ISSUE TITLE
More tools to work with external plugins

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/IITC-Button#3]
I'd like to have such possibilities:
1.  See extended info about installed plugins:
   - metainfo (version, urls)
   - source code (or possibility to save it as file)

2. Add plugin by url
   Actually, it's possible now (i can paster url directly in file chooser), I'd prefer more obvious way, like special input field.

3. Delete plugin

**Comment by johnd0e** [comment]
Just tried to add Bing plugin as external.
I see it in both categories `Map tiles` and `UserScripts`.
And I am able to delete it - there is a button.

I'd like other external plugins be processed exactly: added to both categories, and deletable.

**Comment by modos189** [comment]
In principle, I support, but I will add that viewing the urls of external plugins is not necessary, because they run only on intel.ingress.com/intel

**Comment by johnd0e** [comment]
I mean source urls, from where plugin was downloaded/updated.

**Comment by modos189** [comment]
Done

**Comment by johnd0e** [comment]
> * source code (or possibility to save it as file)

It is currently saved to file named "1" instead of real name.
And I have another wish: possibility to edit source code.

Also it would be nice to see external scripts in categories.
There is no need to divide UserScripts into submenus, better use existing categories.

**Comment by AriMartti** [comment]
Just wanted to customizable optional categorization for external plugins. Standard, internal ones should be as is but I really like to have option to group external plugins some way.

**Comment by elkuku** [comment]
+1 for grouping external plugins  :wink:

**Comment by modos189** [comment]
Issue has been completed, user plugins have been moved from External to the corresponding categories
