### ISSUE TITLE
Header-Parser exception

### ISSUE THREAD

**Issue by McBen** [IITC-CE/IITC-Button#39]
https://github.com/IITC-CE/IITC-Button/blob/d8b5d8be1c1314fbfcfa712727989114cae41f0d/src/helpers.js#L26

will fail if line is empty 

like:
```
// @download sdfsdf

// @author sdfsdf
```

/edit
additional: a missing space between // and @ is also accepted by tampermonkey but not by iitc-button
`//@author sdfsdf`

**Comment by McBen** [comment]
maybe some regex style

```
var regexHeader = /==UserScript==\s*([\s\S]*)\/\/\s*==\/UserScript==/m  // Note: \s\S to match linebreaks
var regexEntry = /\/\/\s*@(\S+)\s+(.*)$/gm  // example match: "\\ @name some text"

var header = regexHeader.exec(pluginCode);
if (header === null) return;
header = header[1]

var entry = regexEntry.exec(header);
while (entry) {
    console.log(entry[1], " = ", entry[2]); // FIXME: entry[2] should be trimmed and " removed
    entry = regexEntry.exec(header);
}
```

**Comment by johnd0e** [comment]
I have another homebrew meta parser here: https://github.com/IITC-CE/ingress-intel-total-conversion/pull/242/files

https://github.com/IITC-CE/ingress-intel-total-conversion/blob/95c6f4d4f4c179b4169d01b3161db068a2aef5c7/core/code/utils_misc.js#L9-L17

**Comment by modos189** [comment]
Made a [fix](https://github.com/IITC-CE/IITC-Button/pull/64/commits/28c69271f00419f8387ff35c678e662202bcf2d2) based on your code. Thanks
