### ISSUE TITLE
Why does it need access to iitc.modos189.ru?

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/IITC-Button#4]

**Comment by modos189** [comment]
IITC updates are downloaded from iitc.modos189.ru.
Extensions cannot interact with sites that are not allowed access.

**Comment by johnd0e** [comment]
> IITC updates are downloaded from iitc.modos189.ru.

Then how it updates external plugins?

**Comment by modos189** [comment]
Currently external plugins are not updated

**Comment by johnd0e** [comment]
Ok then..
And what about Sync?

**Comment by modos189** [comment]
Strict restrictions are imposed only on the sandbox of extension. Plugin Sync runs on the intel page and has access to any url.

**Comment by johnd0e** [comment]
Ok, thanks for explanation!
